export const experienceCursusData = [
  {
    index: 2,
    dDebut: "2023",
    dFin: "Présent",
    title: "Master Expert en développement web",
    explaination: "Formation en alternance",
    schoolName: "Lyon Ynov",
    link: "https://www.ynov.com/campus/lyon/",
  },
  {
    index: 2,
    dDebut: "2022",
    dFin: "2023",
    title: "Licence professionnelle Métiers de l'Informatique Application Web",
    explaination: "Formation en alternance",
    schoolName: "IUT de Clermont-Ferrand",
    link: "https://iut.uca.fr/formations/but-informatique-clermont",
  },
  {
    index: 3,
    dDebut: "2020",
    dFin: "2022",
    title: "DUT Informatique",
    explaination: "Découverte d'une multitude de langages de programmation",
    schoolName: "IUT de Clermont-Ferrand",
    link: "https://iut.uca.fr/formations/but-informatique-clermont",
  },
  {
    index: 4,
    dDebut: "2018",
    dFin: "2020",
    title: "Baccalauréat STI2D",
    explaination: "Spécialité Systèmes d'Information et Numérique (SIN)",
    schoolName: "Lycée Notre Dame du Château",
    link: "https://ndchateau.com/",
  },
];
