export const experienceCursusData = [
  {
    index: 2,
    dDebut: "2023",
    dFin: "KEY_NOW",
    title: "KEY_FORMATION_TITLE1",
    explaination: "KEY_FORMATION_DESC1",
    schoolName: "Lyon Ynov",
    link: "https://www.ynov.com/campus/lyon/",
  },
  {
    index: 2,
    dDebut: "2022",
    dFin: "2023",
    title: "KEY_FORMATION_TITLE2",
    explaination: "KEY_FORMATION_DESC2",
    schoolName: "IUT de Clermont-Ferrand",
    link: "https://iut.uca.fr/formations/but-informatique-clermont",
  },
  {
    index: 3,
    dDebut: "2020",
    dFin: "2022",
    title: "KEY_FORMATION_TITLE3",
    explaination: "KEY_FORMATION_DESC3",
    schoolName: "IUT de Clermont-Ferrand",
    link: "https://iut.uca.fr/formations/but-informatique-clermont",
  },
  {
    index: 4,
    dDebut: "2018",
    dFin: "2020",
    title: "KEY_FORMATION_TITLE4",
    explaination: "KEY_FORMATION_DESC4",
    schoolName: "Lycée Notre Dame du Château",
    link: "https://ndchateau.com/",
  },
];
